In [1]:
import numpy as np
import pandas as pd

In [2]:
df  = pd.read_csv('Pima_Indians_Diabetes_Database.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

We observe that BP and skin thickness do not impact outcome much

In [4]:
# Let's build a small model
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [5]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [6]:
#Since we are building a Neural Network , we need to first scale the input values
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [7]:
X_scaled

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [8]:
X.shape

(768, 8)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.2, random_state = 42)

In [10]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [11]:
model = Sequential()
model.add(Dense(32, input_dim = 8, activation  = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [12]:
model.compile(loss = 'binary_crossentropy', optimizer = 'Adam', metrics = (['accuracy']))
model.fit(X_train, y_train, batch_size = 32, epochs = 100, validation_data = (X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.6321 - loss: 0.6579 - val_accuracy: 0.6429 - val_loss: 0.6375
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7058 - loss: 0.6095 - val_accuracy: 0.6818 - val_loss: 0.5966
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7513 - loss: 0.5540 - val_accuracy: 0.6948 - val_loss: 0.5686
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7694 - loss: 0.5287 - val_accuracy: 0.7013 - val_loss: 0.5472
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7174 - loss: 0.5380 - val_accuracy: 0.7208 - val_loss: 0.5326
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4970 - val_accuracy: 0.7403 - val_loss: 0.5225
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7517 - loss: 0.5110 - val_accuracy: 0.7468 - val_loss: 0.5132
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7890 - loss: 0.4774 - val_accuracy: 0.7597 - val_loss: 0.5079
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8088 - loss: 0.4502 - val_accuracy: 0.7727 - val_loss: 0.5014
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7804 - loss: 0.4643 - val_accuracy: 0.7727 - val_loss: 0.4990
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7627 - loss: 0.4767 - val_accuracy: 0.7727 - val_loss: 0.4995
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7858 - loss: 0.4344 - val_accuracy: 0.7532 - val_loss: 0.4992
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7812 - loss: 0.4534 - val_accuracy: 0.7597 - val_loss: 0.5006
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7974 - loss: 0.4375 - val_accuracy: 0.7597 - val_loss: 0.5001
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7999 - loss: 0.4377 - val_accuracy: 0.7597 - val_loss: 0.4998
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8223 - loss: 0.4050 - val_accuracy: 0.7597 - val_loss: 0.4995
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4356 - val_accuracy: 0.7597 - val_loss: 0.5005
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4368 - val_accuracy: 0.7662 - val_loss: 0.5016
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7925 - loss: 0.4233 - val_accuracy: 0.7597 - val_loss: 0.5040
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7855 - loss: 0.4340 - val_accuracy: 0.7662 - val_loss: 0.5055
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7650 - loss: 0.4385 - val_accuracy: 0.7662 - val_loss: 0.5051
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7745 - loss: 0.4497 - val_accuracy: 0.7662 - val_loss: 0.5062
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7760 - loss: 0.4365 - val_accuracy: 0.7662 - val_loss: 0.5082
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7735 - loss: 0.4389 - val_accuracy: 0.7532 - val_loss: 0.5099
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7909 - loss: 0.4486 - val_accuracy: 0.7597 - val_loss: 0.5096
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7881 - loss: 0.4428 - val_accuracy: 0.7597 - val_loss: 0.5119
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4379 - val_accuracy: 0.7532 - val_loss: 0.5133
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7745 - loss: 0.4385 - val_accuracy: 0.7662 - val_loss: 0.5140
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8075 - loss: 0.4184 - val_accuracy: 0.7727 - val_loss: 0.5142
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7860 - loss: 0.4257 - val_accuracy: 0.7662 - val_loss: 0.5145
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7903 - loss: 0.4136 - val_accuracy: 0.7662 - val_loss: 0.5161
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8018 - loss: 0.4549 - val_accuracy: 0.7662 - val_loss: 0.5163
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7891 - loss: 0.4311 - val_accuracy: 0.7662 - val_loss: 0.5177
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8080 - loss: 0.3968 - val_accuracy: 0.7662 - val_loss: 0.5187
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4213 - val_accuracy: 0.7662 - val_loss: 0.5196
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7926 - loss: 0.4201 - val_accuracy: 0.7662 - val_loss: 0.5190
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7721 - loss: 0.4582 - val_accuracy: 0.7662 - val_loss: 0.5194
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8031 - loss: 0.4293 - val_accuracy: 0.7662 - val_loss: 0.5229
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7743 - loss: 0.4355 - val_accuracy: 0.7662 - val_loss: 0.5249
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7865 - loss: 0.4227 - val_accuracy: 0.7662 - val_loss: 0.5242
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8050 - loss: 0.4095 - val_accuracy: 0.7662 - val_loss: 0.5251
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7986 - loss: 0.4146 - val_accuracy: 0.7662 - val_loss: 0.5258
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7873 - loss: 0.4124 - val_accuracy: 0.7662 - val_loss: 0.5264
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7865 - loss: 0.4216 - val_accuracy: 0.7662 - val_loss: 0.5288
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8010 - loss: 0.4199 - val_accuracy: 0.7597 - val_loss: 0.5300
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7875 - loss: 0.4378 - val_accuracy: 0.7662 - val_loss: 0.5290
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7682 - loss: 0.4358 - val_accuracy: 0.7597 - val_loss: 0.5304
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4292 - val_accuracy: 0.7597 - val_loss: 0.5312
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7836 - loss: 0.4267 - val_accuracy: 0.7662 - val_loss: 0.5323
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8115 - loss: 0.4034 - val_accuracy: 0.7662 - val_loss: 0.5316
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7864 - loss: 0.3959 - val_accuracy: 0.7662 - val_loss: 0.5334
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8261 - loss: 0.3766 - val_accuracy: 0.7662 - val_loss: 0.5352
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7872 - loss: 0.4196 - val_accuracy: 0.7662 - val_loss: 0.5345
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8010 - loss: 0.3887 - val_accuracy: 0.7662 - val_loss: 0.5333
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8063 - loss: 0.4091 - val_accuracy: 0.7662 - val_loss: 0.5331
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7979 - loss: 0.4143 - val_accuracy: 0.7662 - val_loss: 0.5349
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8165 - loss: 0.3931 - val_accuracy: 0.7662 - val_loss: 0.5367
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7802 - loss: 0.4143 - val_accuracy: 0.7662 - val_loss: 0.5362
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7582 - loss: 0.4323 - val_accuracy: 0.7662 - val_loss: 0.5379
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7805 - loss: 0.4219 - val_accuracy: 0.7662 - val_loss: 0.5368
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8028 - loss: 0.4043 - val_accuracy: 0.7662 - val_loss: 0.5372
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7854 - loss: 0.4269 - val_accuracy: 0.7662 - val_loss: 0.5358
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8083 - loss: 0.4115 - val_accuracy: 0.7662 - val_loss: 0.5383
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8031 - loss: 0.4070 - val_accuracy: 0.7662 - val_loss: 0.5368
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7952 - loss: 0.4061 - val_accuracy: 0.7532 - val_loss: 0.5385
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8068 - loss: 0.3938 - val_accuracy: 0.7662 - val_loss: 0.5382
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7988 - loss: 0.4035 - val_accuracy: 0.7662 - val_loss: 0.5379
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8057 - loss: 0.3867 - val_accuracy: 0.7662 - val_loss: 0.5373
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7998 - loss: 0.4019 - val_accuracy: 0.7662 - val_loss: 0.5386
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7900 - loss: 0.4200 - val_accuracy: 0.7662 - val_loss: 0.5407
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7747 - loss: 0.4272 - val_accuracy: 0.7662 - val_loss: 0.5414
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7922 - loss: 0.4125 - val_accuracy: 0.7662 - val_loss: 0.5408
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8083 - loss: 0.4084 - val_accuracy: 0.7662 - val_loss: 0.5402
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8073 - loss: 0.3855 - val_accuracy: 0.7662 - val_loss: 0.5403
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8262 - loss: 0.3880 - val_accuracy: 0.7662 - val_loss: 0.5406
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7804 - loss: 0.4088 - val_accuracy: 0.7662 - val_loss: 0.5416
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7864 - loss: 0.4174 - val_accuracy: 0.7662 - val_loss: 0.5410
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7941 - loss: 0.4020 - val_accuracy: 0.7597 - val_loss: 0.5411
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8069 - loss: 0.3975 - val_accuracy: 0.7662 - val_loss: 0.5424
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8254 - loss: 0.3867 - val_accuracy: 0.7727 - val_loss: 0.5419
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7902 - loss: 0.4009 - val_accuracy: 0.7662 - val_loss: 0.5427
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8186 - loss: 0.3870 - val_accuracy: 0.7662 - val_loss: 0.5441
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8108 - loss: 0.3872 - val_accuracy: 0.7662 - val_loss: 0.5450
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7945 - loss: 0.4050 - val_accuracy: 0.7662 - val_loss: 0.5447
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7975 - loss: 0.3991 - val_accuracy: 0.7662 - val_loss: 0.5455
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8250 - loss: 0.3761 - val_accuracy: 0.7662 - val_loss: 0.5455
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7734 - loss: 0.4186 - val_accuracy: 0.7597 - val_loss: 0.5452
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4056 - val_accuracy: 0.7662 - val_loss: 0.5434
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7985 - loss: 0.4181 - val_accuracy: 0.7727 - val_loss: 0.5430
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7900 - loss: 0.4174 - val_accuracy: 0.7662 - val_loss: 0.5457
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4176 - val_accuracy: 0.7662 - val_loss: 0.5435
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.3963 - val_accuracy: 0.7727 - val_loss: 0.5417
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8048 - loss: 0.4116 - val_accuracy: 0.7727 - val_loss: 0.5406
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8008 - loss: 0.3991 - val_accuracy: 0.7727 - val_loss: 0.5422
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8061 - loss: 0.3847 - val_accuracy: 0.7727 - val_loss: 0.5421
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8169 - loss: 0.3958 - val_accuracy: 0.7662 - val_loss: 0.5412
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8345 - loss: 0.3644 - val_accuracy: 0.7662 - val_loss: 0.5437
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8028 - loss: 0.3981 - val_accuracy: 0.7597 - val_loss: 0.5435
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7898 - loss: 0.4248 - val_accuracy: 0.7597 - val_loss: 0.5443
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7922 - loss: 0.4244 - val_accuracy: 0.7597 - val_loss: 0.5452

Here we need to decide the following hyperparameters ourselves:

1. Number of layers
2. Number of nodes in each layer
3. Activation function
4. Batch Size
5. Number of epochs
6. Loss function
7. Optimizer

It is like trial and error, but can be automated by a library known as **Keras Tuner**

It helps us select the best set of hyperparameters for the dataset for making the model.

In [13]:
#1 Selecting the best optimizer
#first install keras tuner
!pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.7-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.11/dist-packages (from keras-tuner) (3.8.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from keras-tuner) (24.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from keras-tuner) (2.32.3)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (0.0.9)
Requirement already satisfied: h5py in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (3.13.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (0.15.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (2025.4.26)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from optree->keras->keras-tuner) (4.13.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras->keras-tuner) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras->keras-tuner) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.7-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 5.6 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.7 kt-legacy-1.0.5

In [14]:
import kerastuner as kt

<ipython-input-14-5fd8096cdee5>:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

# Steps:
1. Make a function
2. Make a tuner object
3. Pass the function to the tuner object

In [15]:
def build_model(hp): #A standard name of the function (build_model),
#hp = hyperparameter is an object of the hyperparameter class which is passed on to the build_model function
  #Build the model here
  model = Sequential()
  model.add(Dense(32, input_dim = 8, activation = 'relu'))
  model.add(Dense(1, activation = 'sigmoid'))
  model.compile(loss = 'binary_crossentropy', optimizer = hp.Choice('optimizer', values = ['adam', 'sgd', 'rmsprop', 'adadelta']), metrics = (['accuracy']) )
  # Here, we need to select the optimizer from a list
  # Syntax Signature" optimizer = hp.choice(pass a string say'optimizer', after the comma provide a LIST ['adam', 'sgd', 'rmsprop', 'adadelta'] for 'values' parameter)
  # This code will build 4 models, each witha different optimizer provided from the list

  return model

In [16]:
tuner = kt.RandomSearch(build_model, objective = 'val_accuracy', max_trials = 5)
# Try 5 different hyperparameter combinations
# Making an object. The first paramter is the function, 2nd one is the objective, i.e. which thing to reduce/increase, automatically detected
# The tuner will evaluate the combinations using the validation accuracy (val_accuracy) and return the best-performing configuration.

In [17]:
# Start the hyperparameter search process:
# The tuner will try different combinations of hyperparameters and train the model multiple times.

# X_train, y_train: Training data (features and labels) used to train the model.
# epochs=5: The model will train for 5 epochs (iterations over the training data) for each hyperparameter combination.
# validation_data=(X_test, y_test): Validation data used to evaluate the model performance after each epoch.
# The tuner will use these validation results to determine the best hyperparameter combination.
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test), verbose=1)

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.798701286315918

Best val_accuracy So Far: 0.798701286315918
Total elapsed time: 00h 00m 18s

In [18]:
tuner.results_summary()

Results summary
Results in ./untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 3 summary
Hyperparameters:
optimizer: rmsprop
Score: 0.798701286315918

Trial 1 summary
Hyperparameters:
optimizer: adam
Score: 0.7077922224998474

Trial 2 summary
Hyperparameters:
optimizer: sgd
Score: 0.6883116960525513

Trial 0 summary
Hyperparameters:
optimizer: adadelta
Score: 0.5

In [19]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [20]:
model = tuner.get_best_models(num_models = 1)[0]

/usr/local/lib/python3.11/dist-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [21]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.fit(X_train, y_train, batch_size = 32, initial_epoch = 6, epochs = 100, validation_data = (X_test, y_test))
#Since 5 epochs par already trained on best model, so we would like to retain the information

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7773 - loss: 0.5154 - val_accuracy: 0.7792 - val_loss: 0.5258
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7611 - loss: 0.4942 - val_accuracy: 0.7857 - val_loss: 0.5164
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7824 - loss: 0.4778 - val_accuracy: 0.7792 - val_loss: 0.5114
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7485 - loss: 0.4829 - val_accuracy: 0.7792 - val_loss: 0.5070
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7808 - loss: 0.4595 - val_accuracy: 0.7792 - val_loss: 0.5050
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7942 - loss: 0.4425 - val_accuracy: 0.7792 - val_loss: 0.5035
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7758 - loss: 0.4460 - val_accuracy: 0.7727 - val_loss: 0.5029
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7817 - loss: 0.4639 - val_accuracy: 0.7597 - val_loss: 0.5036
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7532 - loss: 0.4737 - val_accuracy: 0.7662 - val_loss: 0.5036
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7943 - loss: 0.4260 - val_accuracy: 0.7727 - val_loss: 0.5033
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7724 - loss: 0.4609 - val_accuracy: 0.7727 - val_loss: 0.5032
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7781 - loss: 0.4388 - val_accuracy: 0.7727 - val_loss: 0.5040
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7689 - loss: 0.4647 - val_accuracy: 0.7662 - val_loss: 0.5044
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7938 - loss: 0.4478 - val_accuracy: 0.7662 - val_loss: 0.5048
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7714 - loss: 0.4421 - val_accuracy: 0.7662 - val_loss: 0.5058
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7717 - loss: 0.4334 - val_accuracy: 0.7662 - val_loss: 0.5059
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8221 - loss: 0.4097 - val_accuracy: 0.7662 - val_loss: 0.5075
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7709 - loss: 0.4422 - val_accuracy: 0.7662 - val_loss: 0.5096
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7838 - loss: 0.4453 - val_accuracy: 0.7662 - val_loss: 0.5103
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7794 - loss: 0.4400 - val_accuracy: 0.7662 - val_loss: 0.5122
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7494 - loss: 0.4739 - val_accuracy: 0.7662 - val_loss: 0.5139
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7836 - loss: 0.4171 - val_accuracy: 0.7662 - val_loss: 0.5155
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8022 - loss: 0.4309 - val_accuracy: 0.7597 - val_loss: 0.5157
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7885 - loss: 0.4338 - val_accuracy: 0.7597 - val_loss: 0.5166
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7696 - loss: 0.4490 - val_accuracy: 0.7597 - val_loss: 0.5193
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8021 - loss: 0.4243 - val_accuracy: 0.7597 - val_loss: 0.5196
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7748 - loss: 0.4413 - val_accuracy: 0.7597 - val_loss: 0.5198
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7762 - loss: 0.4452 - val_accuracy: 0.7597 - val_loss: 0.5214
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7913 - loss: 0.4131 - val_accuracy: 0.7597 - val_loss: 0.5201
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7822 - loss: 0.4433 - val_accuracy: 0.7662 - val_loss: 0.5195
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7703 - loss: 0.4444 - val_accuracy: 0.7662 - val_loss: 0.5206
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8110 - loss: 0.4188 - val_accuracy: 0.7662 - val_loss: 0.5210
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8092 - loss: 0.4122 - val_accuracy: 0.7662 - val_loss: 0.5229
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7692 - loss: 0.4240 - val_accuracy: 0.7597 - val_loss: 0.5248
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7929 - loss: 0.4316 - val_accuracy: 0.7597 - val_loss: 0.5264
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7947 - loss: 0.4320 - val_accuracy: 0.7597 - val_loss: 0.5257
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7760 - loss: 0.4184 - val_accuracy: 0.7597 - val_loss: 0.5264
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7712 - loss: 0.4309 - val_accuracy: 0.7662 - val_loss: 0.5260
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7691 - loss: 0.4371 - val_accuracy: 0.7662 - val_loss: 0.5271
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7946 - loss: 0.4237 - val_accuracy: 0.7662 - val_loss: 0.5265
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7953 - loss: 0.4142 - val_accuracy: 0.7662 - val_loss: 0.5269
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7905 - loss: 0.4383 - val_accuracy: 0.7597 - val_loss: 0.5277
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7979 - loss: 0.4086 - val_accuracy: 0.7597 - val_loss: 0.5291
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7838 - loss: 0.4054 - val_accuracy: 0.7597 - val_loss: 0.5294
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7947 - loss: 0.3918 - val_accuracy: 0.7597 - val_loss: 0.5299
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7790 - loss: 0.4427 - val_accuracy: 0.7597 - val_loss: 0.5295
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7939 - loss: 0.4228 - val_accuracy: 0.7597 - val_loss: 0.5291
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7708 - loss: 0.4614 - val_accuracy: 0.7597 - val_loss: 0.5300
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8045 - loss: 0.4129 - val_accuracy: 0.7597 - val_loss: 0.5302
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7786 - loss: 0.4353 - val_accuracy: 0.7662 - val_loss: 0.5300
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8027 - loss: 0.4210 - val_accuracy: 0.7597 - val_loss: 0.5316
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8050 - loss: 0.4110 - val_accuracy: 0.7597 - val_loss: 0.5325
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8115 - loss: 0.4011 - val_accuracy: 0.7662 - val_loss: 0.5326
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7823 - loss: 0.4383 - val_accuracy: 0.7597 - val_loss: 0.5337
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8136 - loss: 0.3980 - val_accuracy: 0.7597 - val_loss: 0.5347
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7913 - loss: 0.4215 - val_accuracy: 0.7597 - val_loss: 0.5348
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8012 - loss: 0.4037 - val_accuracy: 0.7597 - val_loss: 0.5356
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8041 - loss: 0.4132 - val_accuracy: 0.7532 - val_loss: 0.5354
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8020 - loss: 0.4101 - val_accuracy: 0.7532 - val_loss: 0.5364
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7699 - loss: 0.4509 - val_accuracy: 0.7532 - val_loss: 0.5365
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7952 - loss: 0.4299 - val_accuracy: 0.7532 - val_loss: 0.5373
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7972 - loss: 0.4171 - val_accuracy: 0.7532 - val_loss: 0.5379
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8148 - loss: 0.3850 - val_accuracy: 0.7532 - val_loss: 0.5374
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7793 - loss: 0.4372 - val_accuracy: 0.7532 - val_loss: 0.5395
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8151 - loss: 0.4185 - val_accuracy: 0.7532 - val_loss: 0.5378
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7935 - loss: 0.4197 - val_accuracy: 0.7532 - val_loss: 0.5385
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7947 - loss: 0.4121 - val_accuracy: 0.7532 - val_loss: 0.5401
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8071 - loss: 0.3905 - val_accuracy: 0.7532 - val_loss: 0.5406
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8105 - loss: 0.4073 - val_accuracy: 0.7532 - val_loss: 0.5421
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7828 - loss: 0.4245 - val_accuracy: 0.7532 - val_loss: 0.5431
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8010 - loss: 0.4081 - val_accuracy: 0.7532 - val_loss: 0.5429
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7863 - loss: 0.4319 - val_accuracy: 0.7532 - val_loss: 0.5421
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7962 - loss: 0.4188 - val_accuracy: 0.7532 - val_loss: 0.5423
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7837 - loss: 0.4374 - val_accuracy: 0.7532 - val_loss: 0.5429
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8172 - loss: 0.3853 - val_accuracy: 0.7532 - val_loss: 0.5424
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7713 - loss: 0.4372 - val_accuracy: 0.7532 - val_loss: 0.5430
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7972 - loss: 0.4196 - val_accuracy: 0.7532 - val_loss: 0.5430
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8037 - loss: 0.3896 - val_accuracy: 0.7597 - val_loss: 0.5429
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8220 - loss: 0.3815 - val_accuracy: 0.7468 - val_loss: 0.5450
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8378 - loss: 0.3687 - val_accuracy: 0.7468 - val_loss: 0.5462
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.3820 - val_accuracy: 0.7468 - val_loss: 0.5467
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7867 - loss: 0.4088 - val_accuracy: 0.7532 - val_loss: 0.5450
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7791 - loss: 0.4250 - val_accuracy: 0.7468 - val_loss: 0.5467
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4307 - val_accuracy: 0.7468 - val_loss: 0.5464
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7790 - loss: 0.4234 - val_accuracy: 0.7468 - val_loss: 0.5469
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8011 - loss: 0.3965 - val_accuracy: 0.7468 - val_loss: 0.5461
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8020 - loss: 0.4090 - val_accuracy: 0.7532 - val_loss: 0.5456
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7750 - loss: 0.4246 - val_accuracy: 0.7468 - val_loss: 0.5475
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8256 - loss: 0.3810 - val_accuracy: 0.7468 - val_loss: 0.5476
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7895 - loss: 0.4163 - val_accuracy: 0.7468 - val_loss: 0.5472
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8077 - loss: 0.4139 - val_accuracy: 0.7532 - val_loss: 0.5471
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8335 - loss: 0.3675 - val_accuracy: 0.7532 - val_loss: 0.5471
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8073 - loss: 0.3877 - val_accuracy: 0.7532 - val_loss: 0.5490
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7848 - loss: 0.4190 - val_accuracy: 0.7532 - val_loss: 0.5484

Here accuracy around 75%, SEE val_accuracy

#2. Hyperparameter tuning of number of nodes in a given layer

In [23]:
def build_model(hp):
  model = Sequential()
  units = hp.Int('units', min_value = 8, max_value = 128, step = 8) # build multiple models, can take any step size
  #First model with 8 neurons in hidden layer, 2nd with 16, till 128 and RETURNS THE MODEL WITH THE BEST RESULTS
  model.add(Dense(units = units, input_dim = 8, activation = 'relu'))
  model.add(Dense(1, activation = 'sigmoid'))
  model.compile(loss = 'binary_crossentropy', optimizer = hp.Choice('optimizer', values = ['adam', 'sgd', 'rmsprop', 'adadelta']), metrics = (['accuracy']))
  return model  #total 16 X 4 = 64 models

In [24]:
tuner2 = kt.RandomSearch(build_model, objective = 'val_accuracy', max_trials = 5, directory = 'new_dir') # It will pick the already stored model if dir not added

In [25]:
tuner2.search(X_train, y_train, epochs = 5, validation_data = (X_test, y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.7857142686843872

Best val_accuracy So Far: 0.7857142686843872
Total elapsed time: 00h 00m 16s

In [26]:
tuner2.results_summary()

Results summary
Results in new_dir/untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 0 summary
Hyperparameters:
units: 80
optimizer: adam
Score: 0.7857142686843872

Trial 4 summary
Hyperparameters:
units: 72
optimizer: adam
Score: 0.7857142686843872

Trial 1 summary
Hyperparameters:
units: 120
optimizer: sgd
Score: 0.7402597665786743

Trial 2 summary
Hyperparameters:
units: 24
optimizer: adam
Score: 0.7207792401313782

Trial 3 summary
Hyperparameters:
units: 8
optimizer: adam
Score: 0.6038960814476013

In [27]:
tuner2.get_best_hyperparameters()[0].values

{'units': 80, 'optimizer': 'adam'}

In [28]:
model = tuner2.get_best_models(num_models = 1)[0]

/usr/local/lib/python3.11/dist-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [29]:
model.fit(X_train, y_train, batch_size = 32, initial_epoch = 6, epochs = 100, validation_data = (X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7757 - loss: 0.5070 - val_accuracy: 0.7792 - val_loss: 0.5101
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7503 - loss: 0.4898 - val_accuracy: 0.7792 - val_loss: 0.5012
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7824 - loss: 0.4633 - val_accuracy: 0.7857 - val_loss: 0.4956
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7814 - loss: 0.4453 - val_accuracy: 0.7857 - val_loss: 0.4953
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7996 - loss: 0.4326 - val_accuracy: 0.7727 - val_loss: 0.4964
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7836 - loss: 0.4440 - val_accuracy: 0.7857 - val_loss: 0.4986
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8043 - loss: 0.4201 - val_accuracy: 0.7792 - val_loss: 0.5021
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7743 - loss: 0.4338 - val_accuracy: 0.7727 - val_loss: 0.5046
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7929 - loss: 0.4431 - val_accuracy: 0.7792 - val_loss: 0.5075
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7403 - loss: 0.4698 - val_accuracy: 0.7792 - val_loss: 0.5049
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7879 - loss: 0.4163 - val_accuracy: 0.7727 - val_loss: 0.5093
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8039 - loss: 0.4104 - val_accuracy: 0.7597 - val_loss: 0.5140
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8012 - loss: 0.4085 - val_accuracy: 0.7597 - val_loss: 0.5179
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8211 - loss: 0.4160 - val_accuracy: 0.7597 - val_loss: 0.5164
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7955 - loss: 0.4185 - val_accuracy: 0.7597 - val_loss: 0.5149
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7784 - loss: 0.4413 - val_accuracy: 0.7532 - val_loss: 0.5143
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7660 - loss: 0.4519 - val_accuracy: 0.7597 - val_loss: 0.5164
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.4446 - val_accuracy: 0.7532 - val_loss: 0.5180
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7814 - loss: 0.4286 - val_accuracy: 0.7597 - val_loss: 0.5214
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7840 - loss: 0.4390 - val_accuracy: 0.7597 - val_loss: 0.5215
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7946 - loss: 0.4228 - val_accuracy: 0.7597 - val_loss: 0.5224
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7919 - loss: 0.4291 - val_accuracy: 0.7597 - val_loss: 0.5210
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7894 - loss: 0.4206 - val_accuracy: 0.7597 - val_loss: 0.5208
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7998 - loss: 0.4135 - val_accuracy: 0.7597 - val_loss: 0.5211
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7894 - loss: 0.4282 - val_accuracy: 0.7597 - val_loss: 0.5213
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7743 - loss: 0.4688 - val_accuracy: 0.7532 - val_loss: 0.5243
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8248 - loss: 0.3786 - val_accuracy: 0.7532 - val_loss: 0.5253
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8076 - loss: 0.4149 - val_accuracy: 0.7532 - val_loss: 0.5231
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7989 - loss: 0.4100 - val_accuracy: 0.7532 - val_loss: 0.5215
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8002 - loss: 0.4054 - val_accuracy: 0.7532 - val_loss: 0.5240
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7999 - loss: 0.4080 - val_accuracy: 0.7597 - val_loss: 0.5224
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8115 - loss: 0.4156 - val_accuracy: 0.7597 - val_loss: 0.5267
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8041 - loss: 0.4023 - val_accuracy: 0.7597 - val_loss: 0.5231
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8054 - loss: 0.3983 - val_accuracy: 0.7532 - val_loss: 0.5243
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8156 - loss: 0.3921 - val_accuracy: 0.7532 - val_loss: 0.5235
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7872 - loss: 0.4112 - val_accuracy: 0.7468 - val_loss: 0.5238
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8047 - loss: 0.3899 - val_accuracy: 0.7532 - val_loss: 0.5275
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8072 - loss: 0.3995 - val_accuracy: 0.7532 - val_loss: 0.5292
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8071 - loss: 0.3996 - val_accuracy: 0.7532 - val_loss: 0.5296
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7909 - loss: 0.4430 - val_accuracy: 0.7532 - val_loss: 0.5262
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4127 - val_accuracy: 0.7532 - val_loss: 0.5243
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8152 - loss: 0.3963 - val_accuracy: 0.7532 - val_loss: 0.5257
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7991 - loss: 0.4224 - val_accuracy: 0.7532 - val_loss: 0.5272
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8008 - loss: 0.4096 - val_accuracy: 0.7468 - val_loss: 0.5285
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8164 - loss: 0.4034 - val_accuracy: 0.7532 - val_loss: 0.5296
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8045 - loss: 0.3994 - val_accuracy: 0.7532 - val_loss: 0.5292
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7998 - loss: 0.3996 - val_accuracy: 0.7597 - val_loss: 0.5303
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7967 - loss: 0.4176 - val_accuracy: 0.7532 - val_loss: 0.5323
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7928 - loss: 0.4101 - val_accuracy: 0.7532 - val_loss: 0.5315
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8299 - loss: 0.3821 - val_accuracy: 0.7468 - val_loss: 0.5285
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7870 - loss: 0.4121 - val_accuracy: 0.7532 - val_loss: 0.5264
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8162 - loss: 0.3979 - val_accuracy: 0.7597 - val_loss: 0.5304
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8046 - loss: 0.4245 - val_accuracy: 0.7597 - val_loss: 0.5300
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8040 - loss: 0.4011 - val_accuracy: 0.7468 - val_loss: 0.5282
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8121 - loss: 0.4111 - val_accuracy: 0.7532 - val_loss: 0.5310
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8222 - loss: 0.4047 - val_accuracy: 0.7532 - val_loss: 0.5302
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8147 - loss: 0.3981 - val_accuracy: 0.7468 - val_loss: 0.5320
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8320 - loss: 0.3796 - val_accuracy: 0.7532 - val_loss: 0.5327
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3907 - val_accuracy: 0.7532 - val_loss: 0.5323
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8484 - loss: 0.3555 - val_accuracy: 0.7468 - val_loss: 0.5334
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8375 - loss: 0.3744 - val_accuracy: 0.7532 - val_loss: 0.5349
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8467 - loss: 0.3678 - val_accuracy: 0.7468 - val_loss: 0.5322
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8122 - loss: 0.4006 - val_accuracy: 0.7468 - val_loss: 0.5311
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8278 - loss: 0.3847 - val_accuracy: 0.7468 - val_loss: 0.5339
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8359 - loss: 0.3762 - val_accuracy: 0.7468 - val_loss: 0.5307
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8268 - loss: 0.3837 - val_accuracy: 0.7532 - val_loss: 0.5347
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8051 - loss: 0.4250 - val_accuracy: 0.7532 - val_loss: 0.5360
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8296 - loss: 0.3951 - val_accuracy: 0.7468 - val_loss: 0.5416
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7995 - loss: 0.4000 - val_accuracy: 0.7468 - val_loss: 0.5378
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8196 - loss: 0.3755 - val_accuracy: 0.7468 - val_loss: 0.5369
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8532 - loss: 0.3814 - val_accuracy: 0.7468 - val_loss: 0.5305
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8171 - loss: 0.3739 - val_accuracy: 0.7468 - val_loss: 0.5326
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8329 - loss: 0.3644 - val_accuracy: 0.7468 - val_loss: 0.5339
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8453 - loss: 0.3631 - val_accuracy: 0.7532 - val_loss: 0.5381
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8368 - loss: 0.3621 - val_accuracy: 0.7532 - val_loss: 0.5376
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8377 - loss: 0.3805 - val_accuracy: 0.7468 - val_loss: 0.5353
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8253 - loss: 0.3757 - val_accuracy: 0.7468 - val_loss: 0.5361
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8285 - loss: 0.3812 - val_accuracy: 0.7532 - val_loss: 0.5375
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8283 - loss: 0.3955 - val_accuracy: 0.7468 - val_loss: 0.5341
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8186 - loss: 0.3944 - val_accuracy: 0.7532 - val_loss: 0.5349
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3800 - val_accuracy: 0.7468 - val_loss: 0.5412
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8438 - loss: 0.3694 - val_accuracy: 0.7468 - val_loss: 0.5402
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8455 - loss: 0.3652 - val_accuracy: 0.7403 - val_loss: 0.5437
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8052 - loss: 0.4074 - val_accuracy: 0.7597 - val_loss: 0.5393
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8140 - loss: 0.3863 - val_accuracy: 0.7468 - val_loss: 0.5383
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8338 - loss: 0.3734 - val_accuracy: 0.7468 - val_loss: 0.5423
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8426 - loss: 0.3637 - val_accuracy: 0.7468 - val_loss: 0.5420
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8214 - loss: 0.3911 - val_accuracy: 0.7468 - val_loss: 0.5438
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8346 - loss: 0.3636 - val_accuracy: 0.7403 - val_loss: 0.5419
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8304 - loss: 0.3647 - val_accuracy: 0.7468 - val_loss: 0.5409
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8217 - loss: 0.3702 - val_accuracy: 0.7468 - val_loss: 0.5446
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8307 - loss: 0.3688 - val_accuracy: 0.7403 - val_loss: 0.5495
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8141 - loss: 0.3814 - val_accuracy: 0.7403 - val_loss: 0.5446
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8250 - loss: 0.3799 - val_accuracy: 0.7403 - val_loss: 0.5456

Accuracy here = 75%

# 3. Tuning number of layers

In [30]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(72, input_dim = 8, activation = 'relu')) # first hidden layer
  for i in range(hp.Int('num_layers', min_value = 1, max_value = 10)): # it is two loops actually
    model.add(Dense(72, activation = 'relu')) # jitne bhi layers bane by hyperparameter tuning, for each layer 72 nodes, can change it also

  model.add(Dense(1, activation = 'sigmoid'))

  model.compile(loss = 'binary_crossentropy', optimizer = 'rmsprop', metrics = ['accuracy'])

  return model

In [31]:
tuner3 = kt.RandomSearch(build_model, objective = 'val_accuracy', max_trials = 3, directory = 'new_directory')

In [32]:
tuner3.search(X_train, y_train, epochs = 5, validation_data = (X_test, y_test))

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.7857142686843872

Best val_accuracy So Far: 0.7857142686843872
Total elapsed time: 00h 00m 12s

In [33]:
tuner3.get_best_hyperparameters()[0].values

{'num_layers': 4}

In [34]:
model = tuner3.get_best_models(num_models = 1)[0]

/usr/local/lib/python3.11/dist-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 14 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [35]:
model.fit(X_train, y_train, batch_size = 32, initial_epoch = 6, epochs = 100, validation_data = (X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.7679 - loss: 0.4916 - val_accuracy: 0.7792 - val_loss: 0.5211
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7791 - loss: 0.4615 - val_accuracy: 0.7662 - val_loss: 0.5175
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7918 - loss: 0.4215 - val_accuracy: 0.7143 - val_loss: 0.5347
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7791 - loss: 0.4389 - val_accuracy: 0.7532 - val_loss: 0.5659
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4241 - val_accuracy: 0.7273 - val_loss: 0.5446
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8154 - loss: 0.4095 - val_accuracy: 0.7662 - val_loss: 0.5341
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8266 - loss: 0.4038 - val_accuracy: 0.7208 - val_loss: 0.6101
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8214 - loss: 0.3829 - val_accuracy: 0.7208 - val_loss: 0.5621
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8506 - loss: 0.3563 - val_accuracy: 0.6818 - val_loss: 0.6458
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8232 - loss: 0.3549 - val_accuracy: 0.6948 - val_loss: 0.6645
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8383 - loss: 0.3551 - val_accuracy: 0.7208 - val_loss: 0.5814
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8546 - loss: 0.3280 - val_accuracy: 0.7597 - val_loss: 0.5863
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8512 - loss: 0.3341 - val_accuracy: 0.7597 - val_loss: 0.6285
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8552 - loss: 0.3177 - val_accuracy: 0.7532 - val_loss: 0.6119
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.3127 - val_accuracy: 0.7857 - val_loss: 0.6100
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8724 - loss: 0.3209 - val_accuracy: 0.7597 - val_loss: 0.6581
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8497 - loss: 0.2957 - val_accuracy: 0.7468 - val_loss: 0.6512
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8705 - loss: 0.3107 - val_accuracy: 0.6883 - val_loss: 0.7526
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8636 - loss: 0.2925 - val_accuracy: 0.7662 - val_loss: 0.6652
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8965 - loss: 0.2361 - val_accuracy: 0.7922 - val_loss: 0.7025
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8902 - loss: 0.2723 - val_accuracy: 0.7143 - val_loss: 0.7544
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8772 - loss: 0.2700 - val_accuracy: 0.7273 - val_loss: 0.8212
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9095 - loss: 0.2228 - val_accuracy: 0.7013 - val_loss: 0.8123
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8908 - loss: 0.2505 - val_accuracy: 0.7532 - val_loss: 0.7692
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.2614 - val_accuracy: 0.7078 - val_loss: 0.8840
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9153 - loss: 0.2178 - val_accuracy: 0.7208 - val_loss: 0.9518
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9123 - loss: 0.2109 - val_accuracy: 0.7468 - val_loss: 0.8747
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9240 - loss: 0.1959 - val_accuracy: 0.6623 - val_loss: 1.1802
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9233 - loss: 0.2141 - val_accuracy: 0.7338 - val_loss: 0.9766
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9370 - loss: 0.1625 - val_accuracy: 0.7468 - val_loss: 0.9192
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9329 - loss: 0.1647 - val_accuracy: 0.7597 - val_loss: 0.9845
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9450 - loss: 0.1619 - val_accuracy: 0.6883 - val_loss: 1.0646
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9584 - loss: 0.1379 - val_accuracy: 0.7273 - val_loss: 1.0427
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9433 - loss: 0.1353 - val_accuracy: 0.6688 - val_loss: 1.2729
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9078 - loss: 0.1867 - val_accuracy: 0.6818 - val_loss: 1.2032
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9341 - loss: 0.1528 - val_accuracy: 0.7208 - val_loss: 1.0930
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9638 - loss: 0.1270 - val_accuracy: 0.6753 - val_loss: 1.3036
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9528 - loss: 0.1372 - val_accuracy: 0.7338 - val_loss: 1.1494
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9633 - loss: 0.1077 - val_accuracy: 0.7403 - val_loss: 1.1488
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9654 - loss: 0.1057 - val_accuracy: 0.7013 - val_loss: 1.4383
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9477 - loss: 0.1396 - val_accuracy: 0.7208 - val_loss: 1.3150
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9386 - loss: 0.1406 - val_accuracy: 0.7532 - val_loss: 1.2542
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9738 - loss: 0.0832 - val_accuracy: 0.7208 - val_loss: 1.2957
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9706 - loss: 0.0828 - val_accuracy: 0.7078 - val_loss: 1.3838
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9731 - loss: 0.0846 - val_accuracy: 0.7273 - val_loss: 1.5025
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9829 - loss: 0.0718 - val_accuracy: 0.6364 - val_loss: 1.5413
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9594 - loss: 0.1028 - val_accuracy: 0.7208 - val_loss: 1.6289
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9589 - loss: 0.1015 - val_accuracy: 0.7468 - val_loss: 1.4231
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9856 - loss: 0.0642 - val_accuracy: 0.7208 - val_loss: 1.7714
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9777 - loss: 0.0726 - val_accuracy: 0.7208 - val_loss: 1.6404
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9768 - loss: 0.0687 - val_accuracy: 0.7273 - val_loss: 1.7699
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9866 - loss: 0.0410 - val_accuracy: 0.7143 - val_loss: 1.9394
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9473 - loss: 0.1181 - val_accuracy: 0.7403 - val_loss: 1.7468
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9556 - loss: 0.1029 - val_accuracy: 0.7338 - val_loss: 1.7478
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9877 - loss: 0.0440 - val_accuracy: 0.7403 - val_loss: 1.8876
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9892 - loss: 0.0420 - val_accuracy: 0.7273 - val_loss: 1.8280
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9930 - loss: 0.0284 - val_accuracy: 0.7078 - val_loss: 2.3291
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9823 - loss: 0.0603 - val_accuracy: 0.7273 - val_loss: 2.0457
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9872 - loss: 0.0404 - val_accuracy: 0.7403 - val_loss: 2.0426
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9943 - loss: 0.0281 - val_accuracy: 0.6818 - val_loss: 2.1275
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9815 - loss: 0.0390 - val_accuracy: 0.7078 - val_loss: 2.1722
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9877 - loss: 0.0351 - val_accuracy: 0.7273 - val_loss: 2.1217
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9868 - loss: 0.0480 - val_accuracy: 0.7143 - val_loss: 2.1087
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9936 - loss: 0.0257 - val_accuracy: 0.7403 - val_loss: 2.2573
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9933 - loss: 0.0307 - val_accuracy: 0.7208 - val_loss: 2.3340
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9978 - loss: 0.0121 - val_accuracy: 0.7078 - val_loss: 2.4042
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0436 - val_accuracy: 0.6818 - val_loss: 2.4709
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9768 - loss: 0.0503 - val_accuracy: 0.7208 - val_loss: 2.2265
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9990 - loss: 0.0081 - val_accuracy: 0.7078 - val_loss: 2.4172
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9861 - loss: 0.0337 - val_accuracy: 0.7273 - val_loss: 2.4397
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9786 - loss: 0.0791 - val_accuracy: 0.7273 - val_loss: 2.4157
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9988 - loss: 0.0057 - val_accuracy: 0.7273 - val_loss: 2.4982
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9757 - loss: 0.0509 - val_accuracy: 0.7403 - val_loss: 2.2625
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9813 - loss: 0.0321 - val_accuracy: 0.7273 - val_loss: 2.4846
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9878 - loss: 0.0339 - val_accuracy: 0.7273 - val_loss: 2.4488
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9864 - loss: 0.0350 - val_accuracy: 0.7338 - val_loss: 2.5001
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9913 - loss: 0.0184 - val_accuracy: 0.7078 - val_loss: 2.5598
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9997 - loss: 0.0079 - val_accuracy: 0.7143 - val_loss: 2.6009
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9895 - loss: 0.0290 - val_accuracy: 0.7208 - val_loss: 2.6751
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9955 - loss: 0.0113 - val_accuracy: 0.6818 - val_loss: 2.8065
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9787 - loss: 0.0314 - val_accuracy: 0.7143 - val_loss: 2.9211
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9962 - loss: 0.0177 - val_accuracy: 0.7273 - val_loss: 2.7405
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9926 - loss: 0.0172 - val_accuracy: 0.7208 - val_loss: 2.9055
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9903 - loss: 0.0295 - val_accuracy: 0.7273 - val_loss: 2.7747
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0039 - val_accuracy: 0.7143 - val_loss: 2.9195
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9856 - loss: 0.0640 - val_accuracy: 0.7143 - val_loss: 2.7776
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.7078 - val_loss: 2.9676
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.7013 - val_loss: 3.0420
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9695 - loss: 0.1690 - val_accuracy: 0.7273 - val_loss: 2.9494
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9912 - loss: 0.0210 - val_accuracy: 0.7208 - val_loss: 3.0264
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9922 - loss: 0.0156 - val_accuracy: 0.7013 - val_loss: 2.9078
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.7143 - val_loss: 3.0495
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9758 - loss: 0.0672 - val_accuracy: 0.7208 - val_loss: 3.1288
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9946 - loss: 0.0083 - val_accuracy: 0.7273 - val_loss: 2.9823

Here, Accuracy = 74%

# FINAL COMBINATION MODEL

In [45]:
from keras.layers import Dropout
def build_model(hp):
    model = Sequential()

    # Number of hidden layers (dynamic based on hyperparameter)
    num_layers = hp.Int('num_layers', min_value=1, max_value=10)

    # Adding layers dynamically
    for i in range(num_layers):
        # If it's the first layer, specify input_dim
        if i == 0:
            model.add(Dense(
                hp.Int('units' + str(i), min_value=8, max_value=128, step=8),  # Units per layer
                activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid']),  # Activation function
                input_dim=8  # Input dimension for the first layer (assuming 8 features)
            ))
            model.add(Dropout(hp.Choice('dropout' + str(i), values = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))
        else:  # For subsequent layers, no need for input_dim
            model.add(Dense(
                hp.Int('units' + str(i), min_value=8, max_value=128, step=8),  # Units per layer
                activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid'])  # Activation function
            ))
            model.add(Dropout(hp.Choice('dropout' + str(i), values = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))

    # Add output layer
    model.add(Dense(1, activation='sigmoid'))  # Output layer for binary classification

    # Compile the model with dynamic optimizer choice
    model.compile(
        loss='binary_crossentropy',
        optimizer=hp.Choice('optimizer', values=['adam', 'rmsprop', 'sgd', 'nadam', 'adadelta']),
        metrics=['accuracy']
    )

    return model

In [48]:
tuner_final = kt.RandomSearch(build_model,
                              objective = 'val_accuracy',
                              max_trials = 5,
                              directory = 'Final_dir',
                              project_name = 'Final_Project')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [49]:
tuner_final.search(X_train, y_train, epochs = 5, validation_data = (X_test, y_test))

Trial 5 Complete [00h 00m 04s]
val_accuracy: 0.6558441519737244

Best val_accuracy So Far: 0.7272727489471436
Total elapsed time: 00h 00m 29s

In [50]:
tuner_final.get_best_hyperparameters()[0].values

{'num_layers': 5,
 'units0': 80,
 'activation0': 'relu',
 'dropout0': 0.7,
 'optimizer': 'rmsprop',
 'units1': 88,
 'activation1': 'relu',
 'dropout1': 0.7,
 'units2': 120,
 'activation2': 'tanh',
 'dropout2': 0.7,
 'units3': 16,
 'activation3': 'relu',
 'dropout3': 0.9,
 'units4': 32,
 'activation4': 'relu',
 'dropout4': 0.7,
 'units5': 24,
 'activation5': 'tanh',
 'dropout5': 0.8,
 'units6': 8,
 'activation6': 'tanh',
 'dropout6': 0.8,
 'units7': 64,
 'activation7': 'relu',
 'dropout7': 0.7,
 'units8': 16,
 'activation8': 'tanh',
 'dropout8': 0.6}

In [51]:
model_final = tuner_final.get_best_models(num_models = 1)[0]
model_final.fit(X_train, y_train, epochs = 200, initial_epoch = 5, validation_data = (X_test, y_test))

Epoch 6/200

/usr/local/lib/python3.11/dist-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 14 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.6148 - loss: 0.9217 - val_accuracy: 0.6429 - val_loss: 0.6773
Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5812 - loss: 0.9414 - val_accuracy: 0.6429 - val_loss: 0.6750
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6040 - loss: 0.8416 - val_accuracy: 0.6429 - val_loss: 0.6708
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6044 - loss: 0.8572 - val_accuracy: 0.6429 - val_loss: 0.6688
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6232 - loss: 0.7607 - val_accuracy: 0.6429 - val_loss: 0.6666
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6382 - loss: 0.8148 - val_accuracy: 0.6429 - val_loss: 0.6648
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6207 - loss: 0.7488 - val_accuracy: 0.6429 - val_loss: 0.6628
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6316 - loss: 0.7342 - val_accuracy: 0.6429 - val_loss: 0.6612
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6244 - loss: 0.7709 - val_accuracy: 0.6429 - val_loss: 0.6607
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6293 - loss: 0.6894 - val_accuracy: 0.6429 - val_loss: 0.6591
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6358 - loss: 0.7312 - val_accuracy: 0.6429 - val_loss: 0.6584
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6430 - loss: 0.7187 - val_accuracy: 0.6429 - val_loss: 0.6574
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6706 - loss: 0.7064 - val_accuracy: 0.6429 - val_loss: 0.6568
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6361 - loss: 0.7269 - val_accuracy: 0.6429 - val_loss: 0.6563
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6275 - loss: 0.7240 - val_accuracy: 0.6429 - val_loss: 0.6558
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6449 - loss: 0.6887 - val_accuracy: 0.6429 - val_loss: 0.6555
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6506 - loss: 0.7034 - val_accuracy: 0.6429 - val_loss: 0.6553
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6498 - loss: 0.6885 - val_accuracy: 0.6429 - val_loss: 0.6548
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6401 - loss: 0.6779 - val_accuracy: 0.6429 - val_loss: 0.6546
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6524 - loss: 0.6927 - val_accuracy: 0.6429 - val_loss: 0.6541
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6560 - loss: 0.6608 - val_accuracy: 0.6429 - val_loss: 0.6542
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6685 - loss: 0.6671 - val_accuracy: 0.6429 - val_loss: 0.6539
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6214 - loss: 0.7271 - val_accuracy: 0.6429 - val_loss: 0.6537
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6333 - loss: 0.6889 - val_accuracy: 0.6429 - val_loss: 0.6534
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6290 - loss: 0.6622 - val_accuracy: 0.6429 - val_loss: 0.6532
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6586 - loss: 0.7117 - val_accuracy: 0.6429 - val_loss: 0.6531
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6441 - loss: 0.6738 - val_accuracy: 0.6429 - val_loss: 0.6529
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6530 - loss: 0.6595 - val_accuracy: 0.6429 - val_loss: 0.6527
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6430 - loss: 0.6798 - val_accuracy: 0.6429 - val_loss: 0.6525
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6409 - loss: 0.6772 - val_accuracy: 0.6429 - val_loss: 0.6524
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6390 - loss: 0.6722 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6672 - loss: 0.6642 - val_accuracy: 0.6429 - val_loss: 0.6523
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6628 - loss: 0.6576 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6372 - loss: 0.6621 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6607 - loss: 0.6618 - val_accuracy: 0.6429 - val_loss: 0.6523
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6554 - loss: 0.6552 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6519 - loss: 0.6578 - val_accuracy: 0.6429 - val_loss: 0.6521
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6312 - loss: 0.6865 - val_accuracy: 0.6429 - val_loss: 0.6520
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6788 - loss: 0.6463 - val_accuracy: 0.6429 - val_loss: 0.6520
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6646 - loss: 0.6462 - val_accuracy: 0.6429 - val_loss: 0.6520
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6346 - loss: 0.6668 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6798 - loss: 0.6282 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6770 - loss: 0.6525 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6683 - loss: 0.6506 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6425 - loss: 0.6588 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6514 - loss: 0.6489 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6203 - loss: 0.6692 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6479 - loss: 0.6495 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6425 - loss: 0.6705 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6427 - loss: 0.6617 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6442 - loss: 0.6726 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6104 - loss: 0.7007 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6503 - loss: 0.6534 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6359 - loss: 0.6634 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6379 - loss: 0.6749 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6488 - loss: 0.6977 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6295 - loss: 0.6690 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6542 - loss: 0.6524 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6387 - loss: 0.6582 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6644 - loss: 0.6438 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6452 - loss: 0.6592 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6351 - loss: 0.6653 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6714 - loss: 0.6290 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6613 - loss: 0.6490 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6999 - loss: 0.6274 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6380 - loss: 0.6549 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6451 - loss: 0.6576 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6620 - loss: 0.6460 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6759 - loss: 0.6361 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6371 - loss: 0.6661 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6430 - loss: 0.6549 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6462 - loss: 0.6517 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6647 - loss: 0.6469 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6199 - loss: 0.6748 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6498 - loss: 0.6479 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6647 - loss: 0.6339 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6328 - loss: 0.6720 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6784 - loss: 0.6321 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6404 - loss: 0.6604 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6596 - loss: 0.6669 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6826 - loss: 0.6332 - val_accuracy: 0.6429 - val_loss: 0.6520
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6647 - loss: 0.6648 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6362 - loss: 0.6717 - val_accuracy: 0.6429 - val_loss: 0.6520
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6578 - loss: 0.6366 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6473 - loss: 0.6478 - val_accuracy: 0.6429 - val_loss: 0.6524
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6497 - loss: 0.6501 - val_accuracy: 0.6429 - val_loss: 0.6524
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6597 - loss: 0.6488 - val_accuracy: 0.6429 - val_loss: 0.6525
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6442 - loss: 0.6545 - val_accuracy: 0.6429 - val_loss: 0.6526
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6548 - loss: 0.6778 - val_accuracy: 0.6429 - val_loss: 0.6531
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6574 - loss: 0.6433 - val_accuracy: 0.6429 - val_loss: 0.6535
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6604 - loss: 0.6449 - val_accuracy: 0.6429 - val_loss: 0.6532
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6303 - loss: 0.6872 - val_accuracy: 0.6429 - val_loss: 0.6527
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6434 - loss: 0.6462 - val_accuracy: 0.6429 - val_loss: 0.6530
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6253 - loss: 0.6639 - val_accuracy: 0.6429 - val_loss: 0.6531
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6388 - loss: 0.6537 - val_accuracy: 0.6429 - val_loss: 0.6532
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6539 - loss: 0.6495 - val_accuracy: 0.6429 - val_loss: 0.6534
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6479 - loss: 0.6595 - val_accuracy: 0.6429 - val_loss: 0.6530
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6103 - loss: 0.6701 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6410 - loss: 0.6745 - val_accuracy: 0.6429 - val_loss: 0.6521
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6425 - loss: 0.6571 - val_accuracy: 0.6429 - val_loss: 0.6510
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6760 - loss: 0.6193 - val_accuracy: 0.6429 - val_loss: 0.6504
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6361 - loss: 0.6567 - val_accuracy: 0.6429 - val_loss: 0.6485
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6681 - loss: 0.6230 - val_accuracy: 0.6429 - val_loss: 0.6479
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6433 - loss: 0.6619 - val_accuracy: 0.6429 - val_loss: 0.6475
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6613 - loss: 0.6365 - val_accuracy: 0.6429 - val_loss: 0.6456
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6610 - loss: 0.7043 - val_accuracy: 0.6429 - val_loss: 0.6442
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6572 - loss: 0.6367 - val_accuracy: 0.6429 - val_loss: 0.6426
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6720 - loss: 0.6168 - val_accuracy: 0.6429 - val_loss: 0.6407
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6648 - loss: 0.6434 - val_accuracy: 0.6429 - val_loss: 0.6418
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6403 - loss: 0.6874 - val_accuracy: 0.6429 - val_loss: 0.6405
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6470 - loss: 0.6532 - val_accuracy: 0.6429 - val_loss: 0.6370
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6512 - loss: 0.6288 - val_accuracy: 0.6429 - val_loss: 0.6341
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6507 - loss: 0.6270 - val_accuracy: 0.6429 - val_loss: 0.6310
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6885 - loss: 0.6323 - val_accuracy: 0.6429 - val_loss: 0.6341
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6459 - loss: 0.6637 - val_accuracy: 0.6429 - val_loss: 0.6339
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6400 - loss: 0.6445 - val_accuracy: 0.6429 - val_loss: 0.6304
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6469 - loss: 0.6549 - val_accuracy: 0.6429 - val_loss: 0.6291
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6615 - loss: 0.6202 - val_accuracy: 0.6429 - val_loss: 0.6255
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6352 - loss: 0.6415 - val_accuracy: 0.6429 - val_loss: 0.6252
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6561 - loss: 0.6515 - val_accuracy: 0.6429 - val_loss: 0.6243
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6555 - loss: 0.6391 - val_accuracy: 0.6429 - val_loss: 0.6234
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6408 - loss: 0.6295 - val_accuracy: 0.6429 - val_loss: 0.6216
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6305 - loss: 0.6359 - val_accuracy: 0.6429 - val_loss: 0.6183
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6514 - loss: 0.6538 - val_accuracy: 0.6429 - val_loss: 0.6183
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6389 - loss: 0.6585 - val_accuracy: 0.6429 - val_loss: 0.6151
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6470 - loss: 0.6297 - val_accuracy: 0.6429 - val_loss: 0.6160
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6597 - loss: 0.6353 - val_accuracy: 0.6429 - val_loss: 0.6164
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6420 - loss: 0.6276 - val_accuracy: 0.6429 - val_loss: 0.6145
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6326 - loss: 0.6370 - val_accuracy: 0.6429 - val_loss: 0.6088
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6472 - loss: 0.6472 - val_accuracy: 0.6429 - val_loss: 0.6100
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6492 - loss: 0.6268 - val_accuracy: 0.6429 - val_loss: 0.6086
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6415 - loss: 0.6465 - val_accuracy: 0.6429 - val_loss: 0.6083
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6413 - loss: 0.6522 - val_accuracy: 0.6429 - val_loss: 0.6100
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6464 - loss: 0.6268 - val_accuracy: 0.6429 - val_loss: 0.6164
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6349 - loss: 0.6220 - val_accuracy: 0.6429 - val_loss: 0.6047
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6538 - loss: 0.6365 - val_accuracy: 0.6429 - val_loss: 0.6102
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6918 - loss: 0.6466 - val_accuracy: 0.6429 - val_loss: 0.6167
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6544 - loss: 0.6537 - val_accuracy: 0.6429 - val_loss: 0.6128
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6614 - loss: 0.6299 - val_accuracy: 0.6429 - val_loss: 0.6141
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6836 - loss: 0.5940 - val_accuracy: 0.6429 - val_loss: 0.6091
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6582 - loss: 0.5949 - val_accuracy: 0.6429 - val_loss: 0.6045
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6718 - loss: 0.6153 - val_accuracy: 0.6429 - val_loss: 0.6060
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6552 - loss: 0.5886 - val_accuracy: 0.6429 - val_loss: 0.5969
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6494 - loss: 0.6278 - val_accuracy: 0.6429 - val_loss: 0.5979
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6517 - loss: 0.6534 - val_accuracy: 0.6429 - val_loss: 0.6020
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6491 - loss: 0.6476 - val_accuracy: 0.6429 - val_loss: 0.6058
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6587 - loss: 0.6144 - val_accuracy: 0.6429 - val_loss: 0.5989
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6361 - loss: 0.6202 - val_accuracy: 0.6429 - val_loss: 0.5956
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6716 - loss: 0.6137 - val_accuracy: 0.6429 - val_loss: 0.6002
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6544 - loss: 0.5758 - val_accuracy: 0.6429 - val_loss: 0.5915
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6466 - loss: 0.5946 - val_accuracy: 0.6429 - val_loss: 0.5861
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6597 - loss: 0.6145 - val_accuracy: 0.6429 - val_loss: 0.5884
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6768 - loss: 0.5543 - val_accuracy: 0.6429 - val_loss: 0.5864
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6227 - loss: 0.6162 - val_accuracy: 0.6429 - val_loss: 0.5919
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6462 - loss: 0.5922 - val_accuracy: 0.6429 - val_loss: 0.5992
Epoch 161/200